SET SERVEROUTPUT ON;

------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;

END;
/
-- Test Scenario 1
UPDATE Customers
SET Balance = 5000
WHERE CustomerID = 1;
COMMIT;
SELECT * FROM Customers;
------------------------------------------------------------
-- Scenario 2
-- Create AuditLog Table
------------------------------------------------------------
CREATE TABLE AuditLog(

    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    ActionDate DATE
);
------------------------------------------------------------
-- Trigger to Log Transactions
------------------------------------------------------------
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (TransactionID,AccountID,Amount,ActionDate)
    VALUES

    (:NEW.TransactionID,
     :NEW.AccountID,
     :NEW.Amount,
     SYSDATE);

END;
/
-- Test Scenario 2
INSERT INTO Transactions
VALUES
(
3,
1,
SYSDATE,
500,
'Deposit'
);
COMMIT;
SELECT * FROM AuditLog;
-- Scenario 3
-- Check Deposit and Withdrawal Rules
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW
DECLARE
    balance NUMBER;
BEGIN
    SELECT Balance
    INTO balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;
    IF :NEW.TransactionType='Withdrawal'
       AND :NEW.Amount > balance THEN
        RAISE_APPLICATION_ERROR(
        -20001,
        'Insufficient Balance');
    END IF;
    IF :NEW.TransactionType='Deposit'
       AND :NEW.Amount<=0 THEN

        RAISE_APPLICATION_ERROR(
        -20002,
        'Deposit Amount Must Be Positive');

    END IF;

END;
/
INSERT INTO Transactions
VALUES
(4,1,SYSDATE,200,'Withdrawal');

COMMIT;
SELECT * FROM Transactions;